version: "3.9"

services:
  n8n-aktechno:
    image: n8nio/n8n:latest
    container_name: n8n-aktechno
    restart: unless-stopped
    ports:
      - "5678:5678"

    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - NODE_ENV=${NODE_ENV}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - pilot-network

volumes:
  n8n_data:

networks:
  pilot-network:
    external: true