version: "3.9"

services:
  n8n-automation:
    image: n8nio/n8n:latest
    container_name: n8n-automation
    restart: unless-stopped

    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - NODE_ENV=${NODE_ENV}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-automation.rule=Host(`automation.aktechnoservices.com`)"
      - "traefik.http.routers.n8n-automation.entrypoints=websecure"
      - "traefik.http.routers.n8n-automation.tls.certresolver=cloudflare"
      - "traefik.http.services.n8n-automation.loadbalancer.server.port=5678"

    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - pilot-network

networks:
  pilot-network:
    external: true

volumes:
  n8n_data:
    external: true